main/urls.py
from django.contrib import admin
from django.urls import path
from oficina.views import *
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index, name="index.html"),
    path('pneus/', Pneus, name="pneus.html"),
    path('aros/', Aros, name="aros.html"),
    path('raios/', Raios, name="raios.html"),
    path('farois/', Farois, name="farois.html"),
    path('retrovisores/', Retrovisores, name="retrovisores.html"),
    path('cadastro_servico/', Cadastrar_servico, name="form_servico.html"),
    path('cadastro_cliente/', Cadastrar_cliente, name="form_cliente.html"),
    path('lista_clientes/', Lista_clientes, name="lista_clientes.html"),
    path('editar_cliente/<int:pk>/', Editar_cliente, name="editCli"),
    path('remover_cliente/<int:pk>/', Remover_cliente, name="removCli"),
    path('cadastro_produto/', Cadastrar_produto, name="form_produto.html"),
    path('atendimento/', Atendimento, name="atendimento.html"),
    path('accounts/login/',LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/', logout_aplicação ,name='logout') 

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oficina/models.py
from tkinter.tix import Tree
from django.db import models

# Create your models here.

STATUS= [   
    ('Sim', 'Sim'),
    ('Não',  'Não')
]

class Categoria(models.Model):
    nome = models.CharField(max_length=100)
    
    def __str__(self) -> str:
        return self.nome

# class Marca(models.Model):
    # nome = models.CharField(max_length=100)

    # def __str__(self) -> str:
    #     return self.nome
    
class Produto(models.Model):
    nome = models.CharField(max_length=100)
    perfil = models.IntegerField(blank=True, null=True)
    tamanho = models.IntegerField(blank=True, null=True)
    tipo = models.CharField(max_length=100, blank=True, null=True)
    largura = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    material = models.CharField(max_length=100, blank=True, null=True)
    cor = models.CharField(max_length=100, blank=True, null=True)
    valor_produto = models.DecimalField('Valor do produto', max_digits=5, decimal_places=2)
    quantidade = models.IntegerField()
    imagem = models.ImageField(upload_to='media/', blank=True, null=True, max_length=250) 
    # marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    
    def __str__(self) -> str:
        return self.nome
   
class Servico(models.Model):
    descricao = models.TextField()
    placa = models.CharField(max_length=50)
    valor_servico = models.IntegerField()
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    
    def __str__(self) -> str:
         return self.descricao
      
class Cliente(models.Model):
    nome = models.CharField(max_length=100)
    CPF = models.CharField(max_length=100)
    telefone = models.CharField(max_length=100)
    status_pag = models.CharField(max_length=100, choices=STATUS, blank=True, null=True)
    saldo = models.IntegerField(blank=True, null=True)
    servico = models.ManyToManyField(Servico, blank=True, null=True)

    def __str__(self) -> str:
        return self.nome
    
class Atendimento(models.Model):
    valor_total = models.DecimalField('Valor total', max_digits=5, decimal_places=2, null=True)
    servico = models.OneToOneField(Servico, on_delete=models.CASCADE)
    

main/forms.py
from django import forms
from oficina.models import *


class ClienteForms(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'
        
        widgets = {
            'status_pag': forms.RadioSelect()
        }
        
class ProdutoForms(forms.ModelForm):
    class Meta:
        model = Produto
        fields = '__all__'
        
class ServicoForms(forms.ModelForm):
    class Meta:
        model = Servico
        fields = '__all__'

class AtendimentoForms(forms.ModelForm):
    class Meta:
        model = Atendimento
        fields = '__all__'

oficina/views.py
from django.shortcuts import render
from main.forms import *
from oficina.models import *
from oficina.filters import *
from django.shortcuts import redirect, get_object_or_404
#import sweetify
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from oficina.filters import *

# Create your views here.

@login_required
def Index(request):
    lista_categorias = Categoria.objects.all()
    lista_produtos = Produto.objects.all()
    # lista_marcas = Marca.objects.all()
    produto_filter = ProdutoFilter(request.GET, queryset=lista_produtos)
    # marcas_filter = MarcaFilter(request.GET, queryset=lista_marcas)
    
    context = {
        # 'marcas': marcas_filter,
        'categorias': lista_categorias,
        'produtos': lista_produtos,
        'filter': produto_filter,
        }
    return render (request, 'index.html', context)  

def Lista_clientes(request):
    lista_cli = Cliente.objects.all()
    return render (request, "lista_clientes.html", {'lista_cli' : lista_cli })

def Cadastrar_cliente(request):
    if request.method == 'POST':
        form_cliente = ClienteForms(request.POST)
        if form_cliente.is_valid():
            form_cliente.save()
            form_cliente = ClienteForms()
            return redirect('index.html')
    else:
        form_cliente = ClienteForms()
    
    return render (request,"form_cliente.html", { 'form_cliente' : form_cliente }) 

def Editar_cliente(request, pk):
    edit_cliente = get_object_or_404(Cliente, pk=pk)
    editCli = ClienteForms(request.POST or None, instance=edit_cliente)
    if editCli.is_valid():
        editCli.save()
        return redirect("lista_clientes.html")

    return render (request, "form_cliente.html", {'editCli' : editCli})

def Remover_cliente(request, pk):
    remov_cliente = get_object_or_404(Cliente, pk=pk)
    remov_cliente.delete()
    return redirect("lista_clientes.html")    

def Cadastrar_produto(request):
    if str(request.method) == 'POST':
        form_produto = ProdutoForms(request.POST, request.FILES)
        if form_produto.is_valid():
            form_produto.save()
            form_produto = ProdutoForms()
    else:
        form_produto = ProdutoForms()
    
    return render (request,"form_produto.html", { 'form_produto' : form_produto })

def Cadastrar_servico(request):
    if request.method == 'POST':
        form_servico = ServicoForms(request.POST)
        if form_servico.is_valid():
            form_servico.save()
            form_servico = ServicoForms()
    else:
        form_servico = ServicoForms()
    
    return render (request,"form_servico.html", { 'form_servico' : form_servico })

def Pneus(request):
    lista_pneus = Produto.objects.all()
    return render (request, "pneus.html", {'pneus' : lista_pneus})

def Aros(request):
    lista_aros = Produto.objects.all()
    return render (request, "aros.html", {'aros' : lista_aros})

def Raios(request):
    lista_raios = Produto.objects.all()
    return render (request, "raios.html", {'raios' : lista_raios})

def Farois(request):
    lista_farois = Produto.objects.all()
    return render (request, "farois.html", {'farois' : lista_farois})

def Retrovisores(request):
    lista_retrovisores = Produto.objects.all()
    return render (request, "retrovisores.html", {'pneus' : lista_retrovisores})

def Atendimento(request):

    if request.method == 'POST':
        form_atend = AtendimentoForms(request.POST)
        if form_atend.is_valid():
            form_atend.save()
            form_atend = AtendimentoForms()
    else:
        form_atend = AtendimentoForms()
    return render (request, "atendimento.html", { 'form_atend' : form_atend })

def logout_aplicação(request):
    logout(request)
    return redirect('login')

oficina/templates/aros.html
{% extends 'base.html' %}

{% block conteudo %}

    <h1>OLÁ</h1>

{% endblock %}

oficina/templates/atendimento.html
{% extends 'base.html' %}

<h1>olá</h1>

oficina/templates/base.html
<!DOCTYPE html>
{% load static %} {% load crispy_forms_tags %}
<html lang="pt-br">
  <head>
    <meta charset="utf-8" />
    <!-- Link BoxIcons  -->
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" type="text/css" href="..\static\css\style.css" />
    <!-- <link rel="icon" href="\static\img\LOGO JC MOTO PEÇAS.png" width="30px"> icone na barra do navegador-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"
    />

    <!-- Esse Link aqui -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
      integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I"
      crossorigin="anonymous"
    />
    <!-- Esse Link aqui -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <script src="..\static\js\jquery-3.6.2.js"></script>

    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"
    ></script>
    <title>JC Moto Peças</title>
  </head>
  <body style="min-width: 372px">
    <nav
      class="navbar navbar-expand-lg navbar-dark border-bottom shadow-sm mb-3"
      style="background-color: #11101d"
    >
      <div class="container">
        <a class="navbar-brand" href=" {% url 'index.html' %} "
          >JC Moto peças</a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target=".navbar-collapse"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>
    <div class="sidebar">
      <div class="logo-details">
        <i class="bx bx-wrench icon"></i>
        <div class="logo_name">
          <a class="navbar-brand" href=" {% url 'index.html' %} ">
            JC MotoPeças</a
          >
        </div>
        <i class="bx bx-menu" id="buttom"></i>
      </div>
      <ul class="nav-list">
        <li>
          <a href=" {% url 'form_produto.html' %} ">
            <i class="bx bx-list-plus"></i>
            <span class="links_name">Cadastrar Produto</span>
          </a>
          <span class="tooltip">Cadastrar Produto</span>
        </li>
        <li>
          <a href=" {% url 'form_cliente.html' %} ">
            <i class="bx bx-user"></i>
            <span class="links_name">Cadastrar Cliente</span>
          </a>
          <span class="tooltip">Cadastrar Cliente</span>
        </li>
        <li>
          <a href=" {% url 'form_servico.html' %} ">
            <i class="bx bx-cog"></i>
            <span class="links_name">Cadastrar Serviço</span>
          </a>
          <span class="tooltip">Cadastrar Serviço</span>
        </li>
        <li>
          <a href="{% url 'logout' %}">
            <i class="bx bx-log-out"></i>
            <span class="links_name">Logout</span>
          </a>
          <span class="tooltip">Sair</span>
        </li>
      </ul>
    </div>
    <script>
      let sidebar = document.querySelector(".sidebar");
      let closeBtn = document.querySelector("#buttom");
      let searchBtn = document.querySelector(".bx-search");

      closeBtn.addEventListener("click", () => {
        sidebar.classList.toggle("open");
        menuBtnChange(); //calling the function(optional)
      });

      // following are the code to change sidebar button(optional)
      function menuBtnChange() {
        if (sidebar.classList.contains("open")) {
          closeBtn.classList.replace("bx-menu", "bx-menu-alt-right"); //replacing the iocns class
        } else {
          closeBtn.classList.replace("bx-menu-alt-right", "bx-menu"); //replacing the iocns class
        }
      }
    </script>

    <main class="mb-5 pb-5 mb-md-0">{% block conteudo %} {% endblock %}</main>

    <div style="height: 273px" class="d-block d-md-none"></div>
    <div style="height: 153px" class="d-none d-md-block d-lg-none"></div>
    <div style="height: 129px" class="d-none d-lg-none"></div>

    <footer
      class="border-top fixed-bottom text-muted bg-secondary site-footer"
      style="position: relative initial"
    >
      <div class="container">
        <div class="row py-3">
          <div class="col-12 col-md-4 text-center text-md-left text-dark">
            &copy; 2022 - JC Motos
          </div>
          <div class="col-12 col-md-4 text-center">
            <a class="text-decoration-none text-dark" href=""
              >Politicas de privacidade</a
            >
          </div>
          <div class="col-12 col-md-4 text-center text-md-right">
            <a class="text-decoration-none text-dark" href=""
              >Contato para suporte</a
            >
          </div>
        </div>
      </div>
    </footer>

    <script src="{% static 'js/utils.js' %}"></script>
    <script src="{% static 'js/jquery-1.2.6.pack.js' %}"></script>
    <script src="{% static 'js/jquery.maskedinput-1.1.4.pack.js' %}"></script>
  </body>
</html>

oficina/templates/farois.html
{% extends 'base.html' %}

{% block conteudo %}

    <h1>Olá</h1>

{% endblock %}

oficina/templates/form_cliente.html
{% extends 'base.html' %}

{% block conteudo %}

<div class="container">
    <form method="post">
        <div class="row">
            {% csrf_token %}
            <div class="col-sm-12 col-md6">
                <fieldset class="row">
                    <legend class="mb-3" style="font-size: 30px; center;">Cadastro de novo cliente</legend>
                    <div class="mb-3">
                        <label for="txtnome" class="form-label">Nome</label>
                        <input class="form-control" type="text" id="txtnome" {{ form_cliente.nome }}
                    </div>
                    <div class="col-md-6 col-xl-4 mb-3">
                        <label class="form-label" for="txtCPF">CPF</label>
                        <span class="text-muted">(somente numeros)</span>
                        <input class="form-control" type="text" id="txtCPF" {{ form_cliente.CPF }}
                    </div>
                    <div class="col-md-6 col-xl-4 mb-3">
                        <label class="form-label" for="txtTEL">Telefone</label>
                        <span class="text-muted">(somente numeros)</span>
                        <input class="form-control" type="text" id="txtTEL" {{ form_cliente.telefone }}
                    </div>
                    <div class="col-md-6 col-xl-4 mb-3">
                        <label class="form-label" for="txtsaldo">Saldo</label>
                        <input class="form-control" type="text" id="txtsaldo" {{ form_cliente.saldo }}
                    </div>
                    <div class="mb-3">
                        <label for="txtnome" class="form-label">Status</label>
                        {{ form_cliente.status_pag }}
                    </div>
                    <div class="mb-3">
                        <label for="txtnome" class="form-label">Serviço</label>
                        <br>
                        {{ form_cliente.servico }}
                    </div>
                    
                </fieldset>
            </div>
            <div class="col-sm-12 col-md6">
            </div>
        </div>
        <div class="form-check mb-3">
            <input class="btn btn-primary" type="submit" value="Cadastrar">
        </div>
    </form>
    <a href="{% url 'lista_clientes.html' %}">
        <input class="btn btn-primary" type="submit" value="Lista de clientes">
    </a>
</div>

{% endblock %}

oficina/templates/form_produto.html
{% extends 'base.html' %}
{% load static %}
{% block conteudo %}
<div class="container">
    <form method="post" enctype="multipart/form-data" id="form">
        <div class="row">
            {% csrf_token %}
            <div class="col-sm-12 col-md6">
                <fieldset class="row">
                    <legend class="mb-3" style="font-size: 30px center">Cadastro de nova peça</legend>
                    <div class="mb-3">
                        <label for="txtnome" class="form-label" id="categoria">Categoria</label> <br>
                        <select name="categoria" id="select">
                            <option id="val" value={{ form_produto.categoria }}</option>
                            
                        </select>
                
                    </div>



                    <div class="mb-3" id="marca" >
                        <label for="txtnome" class="form-label">Marca</label> <br>
                        {{ form_produto.nome }}
                    </div>
                    <div style="display: none;" class="col-md-6 col-xl-4 mb-3" id="perfil">
                        <label class="form-label" for="txtPerfil">Perfil</label>
                        <input class="form-control" type="text" id="txtPerfil" {{ form_produto.perfil }} </div>
                        <div style="display: none;" class="col-md-6 col-xl-4 mb-3" id="tamanho">
                            <label class="form-label" for="txttamanho">Tamanho</label>
                            <input class="form-control" type="text" id="txttamanho" {{ form_produto.tamanho }} </div>
                            <div style="display: none;" class="col-md-6 col-xl-4 mb-3" id="tipo">
                                <label class="form-label" for="txtTipo">Tipo</label>
                                <input class="form-control" type="text" id="txtTipo" {{ form_produto.tipo }} </div>
                                <div style="display: none;" class="col-md-6 col-xl-4 mb-3" id="largura">
                                    <label class="form-label" for="txtLargura">Largura</label>
                                    <input class="form-control" type="text" id="txtLargura" {{ form_produto.largura }}
                                        </div>
                                    <div style="display: none;" class="col-md-6 col-xl-4 mb-3" id="material">
                                        <label class="form-label" for="txtMaterial">Material</label>
                                        <input class="form-control" type="text" id="txtMaterial" {{form_produto.material }} 
                                    </div>
                                        <div style="display: none;" class="col-md-6 col-xl-4 mb-3" id="cor">
                                            <label class="form-label" for="txtCor">Cor</label>
                                            <input class="form-control" type="text" id="txtCor" {{ form_produto.cor }}
                                                </div>
                                            <div style="display: none;" class="col-md-6 col-xl-4 mb-3" id="valor">
                                                <label class="form-label" for="txtValor">Valor</label>
                                                <input class="form-control" type="text" id="txtValor" {{ form_produto.valor_produto }}
                                            </div>
                                                <div style="display: none;" class="col-md-6 col-xl-4 mb-3" id="quant">
                                                    <label class="form-label" for="txtQuantidade">Quantidade</label>
                                                    <input class="form-control" type="text" id="txtQuantidade" {{ form_produto.quantidade }}
                                                </div>
                                                    <div style="display: none;" class="mb-3" id="img">
                                                        <label for="txtnome" class="">Adicionar imagem</label> <br>
                                                        {{ form_produto.imagem }}
                                                    </div>

                            

                </fieldset>
            </div>
        </div>
        <div style="display: none;" class="form-check mb-3" id="btn">
            <input class="btn btn-primary" type="submit" value="Cadastrar">
        </div>
        
    </form>

    <script src="../static/js/ocultar.js"></script>
</div>

{% endblock %}

oficina/templates/form_servico.html
{% extends 'base.html' %}

{% block conteudo %}

<div class="container">
    <form method="post">
        <div class="row">
            {% csrf_token %}
            <div class="col-sm-12 col-md6">
                <fieldset class="row">
                    <legend class="mb-3" style="font-size: 30px; center;">Cadastro de Serviço</legend>
                    <div class="col-md-6 col-xl-7 mb-3">
                        <label class="form-label" for="txtTEL">Placa do veiculo</label>
                        <input class="form-control" type="text" id="txtPLA" {{ form_servico.placa }} 
                    </div> 
                    <div class="col-md-6 col-xl-7 mb-3">
                        <label class="form-label" for="txtsaldo">Peças usadas</label> <br>
                        {{ form_servico.produto }}
                    </div>
                    <div class="mb-3">
                        <label for="txtnome" class="form-label">Valor do serviço (R$) </label><br>
                        {{ form_servico.valor_servico }}
                    </div>
                    <div class="mb-3">
                        <label for="txtnome" class="form-label">Descrição do serviço</label>
                        <br>
                        {{ form_servico.descricao }}
                    </div>
                    
                </fieldset>
            </div>
            <div class="col-sm-12 col-md6">
            </div>
        </div>
        <div class="form-check mb-3">
            <input class="btn btn-primary" type="submit" value="Cadastrar">
        </div>
    </form>
</div>

{% endblock %}

oficina/templates/index.html
{% extends 'base.html' %}

{% block conteudo %}
    <div class="container">
        <div class="row">

            <div class="col-12 col-md-7">
                <div class="justify-content-center justify-content-md-start mb-3 mb-md-0">
                    <form class="ml-3 d-inline-block" action="">
                        <select class="form-select form-select-sm" name="categoria" id="id_categoria" onchange="this.form.submit();" >
                            <option value="" disabled selected>Filtrar por categoria</option>
                            <option value="">Todos</option>
                            {% for Categoria in categorias %}
                                <option value="{{ Categoria.id }}">{{ Categoria.nome }}</option>
                            {% endfor %}
                        </select>
                    </form>
                </div>
            </div>

            <div class="col-12 col-md-5">
                <form class="d-flex flex-row-reverse justify-content-center justify-content-md-start" action="">
                    <div class="input-group input-group-sm">
                        <input class="form-control" placeholder="Digite aqui o que procura" type="text" name="nome__icontains" id="id_nome__icontains">
                        <button class="btn btn-danger">
                            Buscar
                        </button>
                    </div>
                </form>
            </div>

        </div>
    </div>

    <div class="container">
        <div class="row">
        </div>
        <hr class="mt-3">
        <div class="row">
            {% for produtos in filter.qs %}
            <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 d-flex align-items-stretch mb-3">
                <div class="card text-center bg-light-">
                    <img src="media/{{ produtos.imagem }}" alt="Imagem do produto">
                    <div class="card-header">
                        R$ {{ produtos.valor_produto }}
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"> {{ produtos.categoria }}</h5>
                        <p class="card-text">Marca: {{ produtos.nome }}  perfil: {{ produtos.perfil }}, largura: {{ produtos.largura }}, tamanho do aro: {{ produtos.tamanho }}</p>
                        
                    </div> 
                    <div class="card-footer align-items-md-center">
                        <form class="d-block" action="">
                            <button class="btn btn-info">
                                Adicionar 
                            </button>
                            <small class="text-success"><br> {{ produtos.quantidade }} peças em estoque <br></small>
                        </form>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

oficina/templates/lista_clientes.html
{% extends 'base.html' %}

{% block conteudo %}
{% csrf_token %}

<div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered table-md">
        <tr>
          <th>#</th>
          <th>Nome</th>
          <th>Telefone</th>
          <th>Saldo</th>
          <th class="col-md-2 center-block">Ações</th>
        </tr>
        {% for Cliente in lista_cli  %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ Cliente.nome }}</td>
            <td>{{ Cliente.telefone }}</td>
            <td> R$ {{ Cliente.saldo }},00 </td>
                <td class="col-md-2 center-block text-center">
                    <a href="{% url 'editCli'  Cliente.id %}" class="btn btn-primary">Editar</a>
                    <a href="{% url 'removCli'  Cliente.id %}" class="btn btn-danger">Remover</a>
                </td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
{% endblock %}

oficina/templates/login.html
<!DOCTYPE html>
<html lang="pt">
  <head>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css" />
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
  </head>

  <body style="background-color: black;">
    <div id="login">
      <div class="container">
        <div id="login-row" class="row justify-content-center align-items-center">
          <div id="login-column" class="col-md-6">
            <div id="login-box" class="col-md-12">
              <form id="login-form" class="form" action="" method="post">
                {% csrf_token %}
                <div class="text-center text-white pt-5">
                  <img src="\static\img\LOGO JC MOTO PEÇAS.png" alt="" width="200px" style="align-content: center;">
                </div>
                <h3 class="text-center text-info">Login</h3>
                <div class="form-group">
                  <label for="username" class="text-info">Usuário:</label><br />
                  <input style="background-color: black;" placeholder="Digite seu usuário" type="text" name="username" id="username" class="form-control" />
                </div>
                <div class="form-group">
                  <label for="password" class="text-info">Senha:</label><br />
                  <input style="background-color: black;" placeholder="Digite sua senha" type="password" name="password" id="password" class="form-control" />
                </div>
                <div class="form-group">
                  <input type="submit" name="submit" class="btn btn-info btn-md" value="Entrar"/>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

oficina/templates/pneus.html
{% extends 'base.html' %}

{% block conteudo %}

    <h1>Olá</h1>

{% endblock %}

oficina/templates/raios.html
{% extends 'base.html' %}

{% block conteudo %}

    <h1>Olá</h1>

{% endblock %}

oficina/templates/retrovisores.html
{% extends 'base.html' %}

{% block conteudo %}

    <h1>Olá</h1>

{% endblock %}